language: python
python:
  - "3.5"
before_install:
  - pip install PyVCF
  - pip install requests
  - pip install PyYAML
  - pip install pandas
  - pip install networkx
  - pip install simanneal
  - pip install biopython
install: true
script:
  - python3 -m unittest discover -v
  - prove --recurse --verbose
