language: python
python:
  - "3.5"
before_install:
  - pip install PyVCF
  - pip install requests
  - pip install PyYAML
install: true
script:
<<<<<<< .merge_file_RjLPGI
  - python3 -m unittest discover -v
=======
  - TEST_FLAG=1 python3 -m unittest discover -v
>>>>>>> .merge_file_MujCqF
  - prove --recurse --verbose
